name: "Setup nf-test"
description: "Install nf-test and add it to the PATH"
author: "nf-core"
inputs:
  version:
    description: "The nf-test version to download (if necessary) and use. Example: 0.8.0. Installs latest by default"
    required: false
    default: 0.9.0 # latest
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "navigation"
  color: "green"
