on:
  # PRs and push to main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: test nf-test installation
jobs:
  test:
    runs-on: ubuntu-latest
    name: A test to install nf-test
    strategy:
      matrix:
        NF-TEST_VER:
          - "0.9.3"
        with-pdiff:
          - true
          - false
        with-fast-diff:
          - false
        include:
          - NF-TEST_VER: "0.9.3"
            with-pdiff: false
            with-fast-diff: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: nf-core/setup-nextflow@893c28b667aedeba26e37f296d260ccc5bc4d914 # v3.0.1

      - name: nf-test install action step
        uses: ./
        with:
          version: "${{ matrix.NF-TEST_VER }}"
          install-pdiff: "${{ matrix.with-pdiff }}"
          install-fast-diff: "${{ matrix.with-fast-diff }}"
      - name: Smoke test
        run: nf-test version
      - name: Show diff viewer output (snapshot mismatch)
        run: nf-test test tests/hello.nf.test || true
